# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

right_format = """
$cmd_duration\
$env_var
"""

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '‚ùØ' symbol in the prompt with '‚ûú'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[‚ûú](bold green)' # The 'success_symbol' segment is being set to '‚ûú' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
format = 'üçÖ[$path]($style)[$read_only]($read_only_style) '
truncation_length = 0
truncation_symbol = '‚Ä¶/'
truncate_to_repo = false
style = 'bold #82AAFF'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_status]
style = 'bold #82AAFF'

[cmd_duration]
format = '[$duration]($style) '

[env_var.all_proxy]
variable = 'all_proxy'
format = '[$env_value]($style)'
default = ''
style = 'bold #82AAFF'

[java]
format = '[${symbol}(${version} )]($style)'

[rust]
format = '[$symbol($version )]($style)'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[nodejs]
format = '[$symbol($version )]($style)'

[lua]
format = '[$symbol($version )]($style)'

[golang]
format = '[$symbol($version )]($style)'

[c]
format = '[$symbol($version(-$name) )]($style)'
